creating random with tf.random

In [1]:
import tensorflow as tf

2026-01-27 21:42:11.046419: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-01-27 21:42:11.078894: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-01-27 21:42:11.837520: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


In [3]:
branch_1 = tf.random.Generator.from_seed(23)
branch_1 = branch_1.normal(shape = (3 , 4))
branch_2 = tf.random.Generator.from_seed(23)
branch_2 = branch_2.normal(shape = (3 , 4))

branch_1 , branch_2 , branch_1 == branch_2

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 0.11754749,  0.03493892, -1.5700307 ,  0.44575813],
        [ 0.10944033, -0.80357677, -1.7166729 ,  0.3738578 ],
        [-0.14371012, -0.34646833,  1.1456193 , -0.41599998]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[ 0.11754749,  0.03493892, -1.5700307 ,  0.44575813],
        [ 0.10944033, -0.80357677, -1.7166729 ,  0.3738578 ],
        [-0.14371012, -0.34646833,  1.1456193 , -0.41599998]],
       dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=bool, numpy=
 array([[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])>)