## this notebook is my exercise about intro to algebra

In [2]:
import numpy as np
import tensorflow as tf

2026-02-14 23:36:11.652229: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-02-14 23:36:12.061445: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-02-14 23:36:13.161135: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


### 1. Scalar

what should I Remember:

    1- type(x)
    2- tf.Variable(x , dtype = tf.int16)
    3- tf.add(x , y)
    4- x.numpy()

first I Check Scalars <br>
I use tensorflow as usual for now (so you can't see pytorch code).

In [9]:
x = 5
print(x)
print(type(x))

5
<class 'int'>


as you can see by default we can't use int16 , int32 , float 16 ,...
lets try in tensorflow

In [10]:
x = tf.Variable(6 , dtype = tf.int8)
print(x)
print(type(x))

<tf.Variable 'Variable:0' shape=() dtype=int8, numpy=6>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


well now it seems ok so we can manage memory better


also tensors let us using GPU for processing ... Great

In [11]:
y = tf.Variable(16 , dtype = tf.int8)
sum_xy = tf.add(x , y)
print("lets check x , y , and x+y")
print("x is :" , x)
print("y is :" , y)
print("x + y is :", sum_xy)
#########
print("now lets check shapes")
print("x , y , x + y : ",x.shape , y.shape , sum_xy)

y_prime = y.numpy()
print(y)

lets check x , y , and x+y
x is : <tf.Variable 'Variable:0' shape=() dtype=int8, numpy=6>
y is : <tf.Variable 'Variable:0' shape=() dtype=int8, numpy=16>
x + y is : tf.Tensor(22, shape=(), dtype=int8)
now lets check shapes
x , y , x + y :  () () tf.Tensor(22, shape=(), dtype=int8)
<tf.Variable 'Variable:0' shape=() dtype=int8, numpy=16>


ok that was Cool

### 2. Vectors

What should I remember : 

    1- len(x)
    2- np.array([])
    3- x.T
    4- x.shape
    5- np.zeros()

now lets check vectors

In [14]:
x = [1 , 2, 4] #this is a list
print(len(x))

3


In [18]:
x = np.array([ 1 , 2, 3, 4]) #this is an array
xt = x.T #lets try Transposing
print(x)
print(x.shape)
print(xt)
print(xt.shape)

[1 2 3 4]
(4,)
[1 2 3 4]
(4,)


nothing changed in Transposing <br>
the reason is : we should have (1 , 4) not (4 ,) <br>
so lets try add one dimention with []

In [3]:
x = np.array([[ 1 , 2, 3, 4]]) 
xt = x.T #lets try Transposing
print(x)
print(x.shape)
print(xt)
print(xt.shape)
y = np.zeros(4)
print(y)
print(y.shape)
print(y.T)

[[1 2 3 4]]
(1, 4)
[[1]
 [2]
 [3]
 [4]]
(4, 1)
[0. 0. 0. 0.]
(4,)
[0. 0. 0. 0.]


the result was grat <br>
now lets try on tensorflow <br>
x.T on tf is not available so this is a question that I should find it

In [21]:
x = tf.Variable([[1 , 2, 3, 4]])
print(x)
print(x.shape)
# xt = x.T
# print(xt)
# print(xt.shape)

<tf.Variable 'Variable:0' shape=(1, 4) dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>
(1, 4)
