# this notebook is my exercise about intro to algebra

In [1]:
import numpy as np
import tensorflow as tf

2026-02-15 16:43:26.465728: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-02-15 16:43:26.873991: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-02-15 16:43:28.010774: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


## 1. Scalar

what should I Remember:

    1- type(x)
    2- tf.Variable(x , dtype = tf.int16)
    3- tf.add(x , y)
    4- x.numpy()

first I Check Scalars <br>
I use tensorflow as usual for now (so you can't see pytorch code).

In [2]:
x = 5
print(x)
print(type(x))

5
<class 'int'>


as you can see by default we can't use int16 , int32 , float 16 ,...
lets try in tensorflow

In [3]:
x = tf.Variable(6 , dtype = tf.int8)
print(x)
print(type(x))

<tf.Variable 'Variable:0' shape=() dtype=int8, numpy=6>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


I0000 00:00:1771170210.264730    7292 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 188 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4060, pci bus id: 0000:01:00.0, compute capability: 8.9
I0000 00:00:1771170210.278545    7292 cuda_executor.cc:508] failed to allocate 188.38MiB (197525504 bytes) from device: RESOURCE_EXHAUSTED: : CUDA_ERROR_OUT_OF_MEMORY: out of memory


well now it seems ok so we can manage memory better


also tensors let us using GPU for processing ... Great

In [4]:
y = tf.Variable(16 , dtype = tf.int8)
sum_xy = tf.add(x , y)
print("lets check x , y , and x+y")
print("x is :" , x)
print("y is :" , y)
print("x + y is :", sum_xy)
#########
print("now lets check shapes")
print("x , y , x + y : ",x.shape , y.shape , sum_xy)

y_prime = y.numpy()
print(y)

lets check x , y , and x+y
x is : <tf.Variable 'Variable:0' shape=() dtype=int8, numpy=6>
y is : <tf.Variable 'Variable:0' shape=() dtype=int8, numpy=16>
x + y is : tf.Tensor(22, shape=(), dtype=int8)
now lets check shapes
x , y , x + y :  () () tf.Tensor(22, shape=(), dtype=int8)
<tf.Variable 'Variable:0' shape=() dtype=int8, numpy=16>


ok that was Cool

## 2. Vectors

What should I remember : 

    1- len(x)
    2- np.array([])
    3- x.T
    4- x.shape
    5- np.zeros()

now lets check vectors

In [5]:
x = [1 , 2, 4] #this is a list
print(len(x))

3


In [6]:
x = np.array([ 1 , 2, 3, 4]) #this is an array
xt = x.T #lets try Transposing
print(x)
print(x.shape)
print(xt)
print(xt.shape)

[1 2 3 4]
(4,)
[1 2 3 4]
(4,)


nothing changed in Transposing <br>
the reason is : we should have (1 , 4) not (4 ,) <br>
so lets try add one dimention with []

In [7]:
x = np.array([[ 1 , 2, 3, 4]]) 
xt = x.T #lets try Transposing
print(x)
print(x.shape)
print(xt)
print(xt.shape)

[[1 2 3 4]]
(1, 4)
[[1]
 [2]
 [3]
 [4]]
(4, 1)


the result was grat <br>
now lets try on tensorflow <br>
x.T on tf is not available so this is a question that I should find it

In [8]:
x = tf.Variable([[1 , 2, 3, 4]])
print(x)
print(x.shape)
# xt = x.T
# print(xt)
# print(xt.shape)

<tf.Variable 'Variable:0' shape=(1, 4) dtype=int32, numpy=array([[1, 2, 3, 4]], dtype=int32)>
(1, 4)


## 3. L Norm



L-norms are a way to measure the magnitude or "length" of a vector. They are commonly used in machine learning for regularization, distance calculations, and to understand the scale of vectors. This notebook will cover common L-norms: L1, L2, Squared L2, Max Norm, and Generalized L-p Norms.

### 1. L2 Norm (Euclidean Norm)

The L2 norm, also known as the Euclidean norm, is the most common measure of vector length. It's the distance from the origin to the point represented by the vector.

**Formula:**

||**x**||₂ = √(∑ᵢ |xᵢ|²)

where:

*   **x** is the vector.
*   xᵢ is the i-th element of the vector.
*   ∑ᵢ means summation over all elements of the vector.

### 2. L1 Norm (Manhattan Norm)

The L1 norm, also known as the Manhattan norm or taxicab norm, represents the sum of the absolute values of the vector's components.

**Formula:**

||**x**||₁ = ∑ᵢ |xᵢ|



### 3. Squared L2 Norm

The squared L2 norm is simply the square of the L2 norm.

**Formula:**

||**x**||₂² = ∑ᵢ |xᵢ|²


### 4. Max Norm (L∞ Norm)

The max norm, also known as the infinity norm, is the largest absolute value of the vector's components.

**Formula:**

||**x**||∞ = maxᵢ |xᵢ|

### 5. Generalized L-p Norm

The L-p norm generalizes the concept of L1 and L2 norms.

**Formula:**

||**x**||ₚ = (∑ᵢ |xᵢ|ᵖ)¹/ₚ

**Summary:**

L-norms provide valuable tools for understanding and regularizing machine learning models.  By understanding these different norms, you can better control the behavior and properties of your models.

In [18]:
x = tf.Variable([5. , 2. , 1.])

In [19]:
# 1. L1 Norm
l1_norm = tf.reduce_sum(tf.abs(x))
print(f"L1 Norm: {l1_norm.numpy()}")  # Output: L1 Norm: 8.0

# 2. L2 Norm
l2_norm = tf.norm(x)
print(f"L2 Norm: {l2_norm.numpy()}")  # Output: L2 Norm: 5.477225575051661

# 3. Squared L2 Norm
squared_l2_norm = tf.reduce_sum(tf.square(x))
print(f"Squared L2 Norm: {squared_l2_norm.numpy()}") # Output: Squared L2 Norm: 32.0

# 4. Max Norm
max_norm = tf.reduce_max(tf.abs(x))
print(f"Max Norm: {max_norm.numpy()}") # Output: Max Norm: 5.0

L1 Norm: 8.0
L2 Norm: 5.477225303649902
Squared L2 Norm: 30.0
Max Norm: 5.0
