creating tensors with tf.variable

In [2]:
import tensorflow as tf

2026-01-27 20:57:10.379541: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-01-27 20:57:10.410414: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-01-27 20:57:11.148456: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


In [4]:
changable_tensor = tf.Variable(1)

I0000 00:00:1769543839.940510   92772 gpu_device.cc:2020] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5805 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4060, pci bus id: 0000:01:00.0, compute capability: 8.9


In [5]:
changable_tensor

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

In [6]:
changable_tensor2 = tf.Variable([1])

In [7]:
changable_tensor2

<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([1], dtype=int32)>

In [14]:
changable_tensor3 = tf.Variable([[1, 2, 3 ], [4, 5, 6], [7, 8, 9]])

In [15]:
changable_tensor3

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]], dtype=int32)>

In [17]:
changable_tensor.assign(23)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=23>

In [19]:
changable_tensor

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=23>

In [20]:
changable_tensor2[0].assign(17)

<tf.Variable 'UnreadVariable' shape=(1,) dtype=int32, numpy=array([17], dtype=int32)>

In [21]:
changable_tensor2

<tf.Variable 'Variable:0' shape=(1,) dtype=int32, numpy=array([17], dtype=int32)>

In [22]:
changable_tensor3[0].assign([11,22,33])

<tf.Variable 'UnreadVariable' shape=(3, 3) dtype=int32, numpy=
array([[11, 22, 33],
       [ 4,  5,  6],
       [ 7,  8,  9]], dtype=int32)>

In [23]:
changable_tensor3

<tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
array([[11, 22, 33],
       [ 4,  5,  6],
       [ 7,  8,  9]], dtype=int32)>