tf.constant practice

what should I remember:
1- tf.constant() usage
2- creating multiple dimensions with tf.constant
3- changing the type (like float16 or float32) with dtype
4- ndim results based on the tensor I created

In [1]:
import tensorflow as tf

2026-01-27 18:52:38.005634: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2026-01-27 18:52:38.035588: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-01-27 18:52:38.766047: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


**********this section I practiced n-dimensions with tf.constant integer variables

In [4]:
scale = tf.constant(1)

In [5]:
scale

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [6]:
scale.ndim

0

In [7]:
vector = tf.constant([1 , 2])

In [8]:
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [9]:
vector.ndim

1

In [12]:
vector2 = tf.constant([[1 , 2],
                        [3 , 4]])

In [13]:
vector2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [14]:
vector2.ndim

2

In [16]:
matrix = tf.constant([[[1 , 2] , [5 , 6]] , [[3 , 4] , [7 , 8]]])

In [18]:
matrix

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]], dtype=int32)>

In [17]:
matrix.ndim

3

********* as you can see we can make variant tf.constant with different dimension
now its time to change the type and see results

In [19]:
floatsample = tf.constant(1.1)

In [20]:
floatsample

<tf.Tensor: shape=(), dtype=float32, numpy=1.100000023841858>

In [21]:
floatsample.ndim

0

In [24]:
float16sample = tf.constant([1.0 , 2.1], dtype=tf.float16)

2026-01-27 19:18:16.156200: E tensorflow/core/util/util.cc:131] oneDNN supports DT_HALF only on platforms with AVX-512. Falling back to the default Eigen-based implementation if present.


In [25]:
float16sample

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1. , 2.1], dtype=float16)>

In [27]:
float16sample.ndim

1